### ISSUE TITLE
`Not enough bytes` error when parsing simple 1D float IDX file

### ISSUE THREAD

**Issue by MatthewDaggitt** [kryoxide/mnist-idx#12]
#### Problem

I'm trying to parse the attached file [dataset-rat-4.zip](https://github.com/schrammc/mnist-idx/files/8458826/dataset-rat-4.zip), which contains a simple 1D array of 4 floats `[0.1, 3.0, -2.0, -3.2]`. However `decodeIDXFile` returns `Nothing`. 

After messing around to get the error message as described in https://github.com/schrammc/mnist-idx/issues/11, it is failing on parsing the first float in the actual data portion of the file with the message `Not enough bytes`.

The ByteString that is being read in is 24 bytes long which is correct (4 bytes for the headers, 4 bytes for the first dimension, 16 bytes for the 4 32-bit floats). Stepping through the code in GHCi, I can't see any extraneous `get`s being performed by the `get` method in `instance Binary IDXData` which would cause it to run out of data, so I'm at a bit of a loss about why it's failing... 

#### File origin

For complete information, the file is being generated with the following Python script:
```python
import idx2numpy
import numpy as np

xs = np.array([0.1,3,-2,-3.2]).astype('float32')

f_write = open('dataset-rat-4.idx', 'wb')
idx2numpy.convert_to_file(f_write, xs)
```
I've checked the source code of the `convert_to_file` method and it is writing it out in the correct endian-ness (i.e. big endian). I can also successfully read it back in with the same Python library:
```python
import idx2numpy

idx2numpy.convert_from_file('dataset-rat-4.idx')
```

**Comment by MatthewDaggitt** [comment]
Okay I've tracked the error down to this issue: https://github.com/kolmodin/binary/issues/69. The package `binary`'s encoding of floats and doubles is... not great! It uses 25 bytes per float! Which means that any file produced by this library does not conform to the IDX spec which mandates 4 bytes per float, and likewise this library can't parse spec-compliant IDX files. 

@schrammc what do you think the best approach is? The issue above recommends switching to [CBOR](https://github.com/well-typed/cborg) and Reddit recommends switching to [cereal](https://hackage.haskell.org/package/cereal).

**Comment by MatthewDaggitt** [comment]
Okay so [this table](https://github.com/haskell-perf/serialization#tested-libraries) says that `cereal` is still not compliant with the standard encoding. That leaves `CBOR`/`serialise` as the obvious choice.

**Comment by schrammc** [comment]
Since I don't really want to switch the whole underlying library I'd actually think it might make sense to do some sort of

```
newtype CorrectlyEncodedFloat = CorrectlyEncodedFloat Word32
  deriving newtype Binary
  
toFloat :: CorrectlyEncodedFloat -> Float
toFloat = undefined -- insert bit twiddling / coercing

fromFloat :: Float -> CorrectlyEncodedFloat
fromFloat = undefined --insert bit twiddlng / coercing

```

**Comment by MatthewDaggitt** [comment]
> Since I don't really want to switch the whole underlying library

Out of interest is that because of the amount effort it would take or for some other reason?

Do you know how to do that bit twiddling/coercing off the top of your head? Just asking, because at least if I was going to fix this I think it would be less time to switch libraries then for me to get my head around the bit twiddling :smiling_face_with_tear: 

Also just a heads up that there is a similar bug with the double representation as well.

**Comment by schrammc** [comment]
I pushed a commit to master that *should* fix this using stuff from the std-lib: https://hackage.haskell.org/package/base-4.16.1.0/docs/GHC-Float.html#v:castFloatToWord32

If this fixes your issues I'll cut a new minor release and add some tests tomorrow.

**Comment by MatthewDaggitt** [comment]
Ah that is a neat fix! Yes that works like a charm :+1: Thank you!

**Comment by schrammc** [comment]
Nice, thanks for reporting this 👍

**Comment by MatthewDaggitt** [comment]
No, thank you for responding and fixing it so quickly!
