### ISSUE TITLE
Relax the bound on vector (via Hackage API perhaps?)

### ISSUE THREAD

**Issue by Mikolaj** [kryoxide/mnist-idx#13]
The bound on package vector can be relaxed. I've just tested with `--allow-newer=mnist-idx:vector` on https://github.com/Mikolaj/horde-ad and it works great. This can be easily relaxed as a Hackage revision, without releasing a new version.

**Comment by Mikolaj** [comment]
Or if you add me to the list of Hackage maintainers for the package, I can do that for you: https://hackage.haskell.org/user/MikolajKonarski

**Comment by schrammc** [comment]
How would you feel about me just dropping upper bounds entirely on the dependencies for this?

**Comment by Mikolaj** [comment]
I would feel guilty and enthusiastic. :) Cabal people deem this a bad practice (the lack of bounds prevents automatic and trustworthy solving for a working build plan with newest package versions possible), while IIRC stack people think it's the only sane thing to do (Stackage snapshots fix versions). As a user, I'd absolutely welcome the trade-off. Given that your package, I imagine, is mostly used for teaching, experiments and benchmarks, not for production runs, I expect most users would.

**Comment by schrammc** [comment]
I'll test this with the latest library versions. Provided this works out fine I'll cut a new release dropping upper bounds altogether otherwise I'll just drop the upper bound on `vector`.

**Comment by Mikolaj** [comment]
Ping, ping! :D

**Comment by schrammc** [comment]
Done 👍 I released a patch-version that has no more upper-bounds on dependencies.
