### ISSUE TITLE
No docs on hackage

### ISSUE THREAD

**Issue by m-renaud** [kryoxide/mnist-idx#5]

**Comment by schrammc** [comment]
I put the documentation for the newest version on hackage

**Comment by m-renaud** [comment]
Thanks! FYI, it appears that the "Source" links are broken through.

**Comment by schrammc** [comment]
Yeah, I know but the system for getting them to work is weird and not exactly well documented. So i probably wont take care of getting them to work in the near future.

**Comment by m-renaud** [comment]
Haha, fair enough :P
