### ISSUE TITLE
GHC 9.2.1 support (bump bytestring dep; it works fine for me then)

### ISSUE THREAD

**Issue by Mikolaj** [kryoxide/mnist-idx#9]
Hi! Thank you for the great tool! I think it's safe to just bump the upper bound of the bytestring dep, making this work with GHC 9.2.1.

**Comment by Mikolaj** [comment]
@ping!

**Comment by schrammc** [comment]
Thanks for making this PR!

**Comment by Mikolaj** [comment]
Thank you for merging it. 

BTW, heads up: your blog email and your LinkedIn messages may be bouncing.
